"""Stdlib-only remote Session Workspace agent and its host execution adapter."""

from __future__ import annotations

import errno
import json
from typing import Any

_UNSUPPORTED_LINK_ERRNOS = frozenset({errno.EPERM})
_UNSUPPORTED_REPLACE_ERRNOS = frozenset(
    {
        errno.EPERM,
        errno.EXDEV,
        errno.EOPNOTSUPP,
        getattr(errno, "ENOTSUP", errno.EOPNOTSUPP),
        errno.ENOSYS,
        38,
        95,
    }
)


class WorkspaceAgentStorageError(OSError):
    """Remote mounted-volume mutation failure."""


_PATH_ERRORS = {
    "not_found": FileNotFoundError,
    "conflict": FileExistsError,
    "is_directory": IsADirectoryError,
    "not_directory": NotADirectoryError,
}
_VALUE_ERRORS = {
    "read_bound": "workspace file exceeds read bound",
    "too_large": "workspace file exceeds maximum size",
    "invalid_utf8": "workspace file is not valid UTF-8",
    "cursor": "workspace cursor is invalid",
}


def build_workspace_agent_code(
    *,
    volume_root: str,
    root: str,
    operation: str,
    relative: str,
    allow_missing: bool,
    max_bytes: int,
    limit: int,
    overwrite: bool,
    content_b64: str,
    after: str = "",
    offset: int = 0,
    max_chars: int = 0,
) -> str:
    code = "\n".join(
        (
            "import base64, errno, json, os, stat, time",
            f"volume_root = {volume_root!r}",
            f"root = {root!r}",
            f"relative = {relative!r}",
            f"allow_missing = {allow_missing!r}",
            f"operation = {operation!r}",
            f"max_bytes = {int(max_bytes)!r}",
            f"limit = {int(limit)!r}",
            f"overwrite = {overwrite!r}",
            f"content_b64 = {content_b64!r}",
            f"after = {after!r}",
            f"offset = {int(offset)!r}",
            f"max_chars = {int(max_chars)!r}",
            "def respond(payload):",
            "    print(json.dumps(payload))",
            "    raise SystemExit(0)",
            "def fail(error, **extra):",
            "    respond({'ok': False, 'error': error, **extra})",
            "def decode_page(data):",
            "    try:",
            "        return data.decode('utf-8'), len(data)",
            "    except UnicodeDecodeError as exc:",
            "        if exc.end == len(data) and ('end' in exc.reason or 'truncated' in exc.reason):",
            "            valid = data[:exc.start]",
            "            return valid.decode('utf-8'), len(valid)",
            "        raise",
            "class UnsafePath(Exception):",
            "    pass",
            "class StorageError(Exception):",
            "    def __init__(self, errno_value):",
            "        super().__init__(errno_value)",
            "        self.errno = errno_value",
            "class ReplacementUnsupported(Exception):",
            "    def __init__(self, errno_value):",
            "        super().__init__(errno_value)",
            "        self.errno = errno_value",
            "def open_directory(path, *, dir_fd=None, create=False):",
            "    flags = os.O_RDONLY | os.O_DIRECTORY | getattr(os, 'O_NOFOLLOW', 0)",
            "    try:",
            "        existing = os.stat(path, dir_fd=dir_fd, follow_symlinks=False)",
            "        if stat.S_ISLNK(existing.st_mode):",
            "            raise UnsafePath(path)",
            "    except FileNotFoundError:",
            "        existing = None",
            "    if existing is not None:",
            "        return os.open(path, flags, dir_fd=dir_fd)",
            "    try:",
            "        return os.open(path, flags, dir_fd=dir_fd)",
            "    except FileNotFoundError:",
            "        if not create:",
            "            raise",
            "        try:",
            "            os.mkdir(path, 0o700, dir_fd=dir_fd)",
            "        except FileExistsError:",
            "            pass",
            "        return os.open(path, flags, dir_fd=dir_fd)",
            "def open_chain(*, create=False):",
            "    fds = []",
            "    try:",
            "        volume_fd = open_directory(volume_root)",
            "        fds.append(volume_fd)",
            "        root_parts = os.path.relpath(root, volume_root).split(os.sep)",
            "        if root_parts == ['.'] or root_parts == ['']:",
            "            root_parts = []",
            "        for part in root_parts:",
            "            next_fd = open_directory(part, dir_fd=fds[-1], create=create)",
            "            fds.append(next_fd)",
            "        root_fd = fds[-1]",
            "        return fds, root_fd",
            "    except BaseException:",
            "        for fd in reversed(fds):",
            "            try:",
            "                os.close(fd)",
            "            except OSError:",
            "                pass",
            "        raise",
            "def split_relative(value):",
            "    return [] if value == '.' else value.split('/')",
            "def open_parent(root_fd, parts, *, create=False):",
            "    fds = []",
            "    current_fd = root_fd",
            "    try:",
            "        for part in parts:",
            "            current_fd = open_directory(part, dir_fd=current_fd, create=create)",
            "            fds.append(current_fd)",
            "        return fds, current_fd",
            "    except BaseException:",
            "        for fd in reversed(fds):",
            "            try:",
            "                os.close(fd)",
            "            except OSError:",
            "                pass",
            "        raise",
            "def close_all(fds):",
            "    for fd in reversed(fds):",
            "        try:",
            "            os.close(fd)",
            "        except OSError:",
            "            pass",
            "def entry_for(info, entry_path):",
            "    modified_at = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime(info.st_mtime))",
            "    if stat.S_ISDIR(info.st_mode):",
            "        return {'path': entry_path, 'kind': 'directory', 'byte_size': None, 'modified_at': modified_at}",
            "    return {'path': entry_path, 'kind': 'file', 'byte_size': info.st_size, 'modified_at': modified_at}",
            "def write_all(fd, payload):",
            "    offset = 0",
            "    while offset < len(payload):",
            "        try:",
            "            written = os.write(fd, payload[offset:])",
            "        except InterruptedError:",
            "            continue",
            "        if written <= 0:",
            "            raise OSError('short write')",
            "        offset += written",
            "def fsync_directory(parent_fd):",
            "    try:",
            "        os.fsync(parent_fd)",
            "    except OSError as exc:",
            "        raise StorageError(exc.errno) from exc",
            "def replace_existing(parent_fd, name, payload):",
            "    temporary = f'.fleet-write-{os.getpid()}-{time.time_ns()}'",
            "    fd = None",
            "    temporary_removed = False",
            "    cleanup_errno = None",
            "    try:",
            "        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_NOFOLLOW', 0)",
            "        fd = os.open(temporary, flags, 0o600, dir_fd=parent_fd)",
            "        write_all(fd, payload)",
            "        os.fsync(fd)",
            "        os.close(fd)",
            "        fd = None",
            "        os.replace(temporary, name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)",
            "        temporary_removed = True",
            "        try:",
            "            fsync_directory(parent_fd)",
            "        except StorageError as exc:",
            "            cleanup_errno = exc.errno",
            "        return os.stat(name, dir_fd=parent_fd, follow_symlinks=False), cleanup_errno",
            "    except (FileNotFoundError, FileExistsError):",
            "        raise",
            "    except OSError as exc:",
            f"        if exc.errno in {sorted(_UNSUPPORTED_REPLACE_ERRNOS)!r}:",
            "            raise ReplacementUnsupported(exc.errno) from exc",
            "        raise StorageError(exc.errno) from exc",
            "    finally:",
            "        if fd is not None:",
            "            os.close(fd)",
            "        if not temporary_removed:",
            "            try:",
            "                os.unlink(temporary, dir_fd=parent_fd)",
            "            except OSError:",
            "                pass",
            "def write_new_direct(parent_fd, name, payload):",
            "    fd = None",
            "    created_stat = None",
            "    def cleanup_created():",
            "        if created_stat is None:",
            "            return",
            "        try:",
            "            current = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)",
            "            if (current.st_dev, current.st_ino) == (created_stat.st_dev, created_stat.st_ino):",
            "                os.unlink(name, dir_fd=parent_fd)",
            "        except OSError:",
            "            pass",
            "    try:",
            "        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_NOFOLLOW', 0)",
            "        fd = os.open(name, flags, 0o600, dir_fd=parent_fd)",
            "        created_stat = os.fstat(fd)",
            "        write_all(fd, payload)",
            "        os.fsync(fd)",
            "        fsync_directory(parent_fd)",
            "        return os.fstat(fd)",
            "    except FileExistsError:",
            "        raise",
            "    except OSError as exc:",
            "        cleanup_created()",
            "        raise StorageError(exc.errno) from exc",
            "    except BaseException:",
            "        cleanup_created()",
            "        raise",
            "    finally:",
            "        if fd is not None:",
            "            os.close(fd)",
            "def publish_new(parent_fd, name, payload):",
            "    temporary = f'.fleet-write-{os.getpid()}-{time.time_ns()}'",
            "    fd = None",
            "    temporary_removed = False",
            "    cleanup_errno = None",
            "    try:",
            "        fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_NOFOLLOW', 0), 0o600, dir_fd=parent_fd)",  # noqa: E501 - emitted sandbox code is intentionally one line
            "        write_all(fd, payload)",
            "        os.fsync(fd)",
            "        os.close(fd)",
            "        fd = None",
            "        try:",
            "            os.link(temporary, name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd, follow_symlinks=False)",
            "            pass",
            "        except OSError as exc:",
            "            if exc.errno == errno.EEXIST:",
            "                raise FileExistsError(name) from exc",
            f"            if exc.errno not in {sorted(_UNSUPPORTED_LINK_ERRNOS)!r}:",
            "                raise StorageError(exc.errno) from exc",
            "            direct_stat = write_new_direct(parent_fd, name, payload)",
            "            try:",
            "                os.unlink(temporary, dir_fd=parent_fd)",
            "                temporary_removed = True",
            "            except OSError as cleanup_exc:",
            "                cleanup_errno = cleanup_exc.errno",
            "            return direct_stat, cleanup_errno",
            "        fsync_directory(parent_fd)",
            "        try:",
            "            os.unlink(temporary, dir_fd=parent_fd)",
            "            temporary_removed = True",
            "        except OSError as exc:",
            "            cleanup_errno = exc.errno",
            "        return os.stat(name, dir_fd=parent_fd, follow_symlinks=False), cleanup_errno",
            "    finally:",
            "        if fd is not None:",
            "            os.close(fd)",
            "        if not temporary_removed:",
            "            try:",
            "                os.unlink(temporary, dir_fd=parent_fd)",
            "            except OSError:",
            "                pass",
            "            else:",
            "                temporary_removed = True",
            "def read_existing(parent_fd, name, max_bytes):",
            "    fd = None",
            "    try:",
            "        fd = os.open(name, os.O_RDONLY | getattr(os, 'O_NOFOLLOW', 0), dir_fd=parent_fd)",
            "        data = os.read(fd, max_bytes + 1)",
            "        if len(data) > max_bytes:",
            "            raise StorageError(errno.EFBIG)",
            "        return data",
            "    except OSError as exc:",
            "        if isinstance(exc, StorageError):",
            "            raise",
            "        raise StorageError(exc.errno) from exc",
            "    finally:",
            "        if fd is not None:",
            "            os.close(fd)",
            "def overwrite_existing_direct(parent_fd, name, payload, previous):",
            "    fd = None",
            "    cleanup_errno = None",
            "    try:",
            "        fd = os.open(name, os.O_WRONLY | os.O_TRUNC | getattr(os, 'O_NOFOLLOW', 0), dir_fd=parent_fd)",
            "        write_all(fd, payload)",
            "    except OSError as exc:",
            "        if fd is not None:",
            "            os.close(fd)",
            "            fd = None",
            "        try:",
            "            restore_fd = os.open(name, os.O_WRONLY | os.O_TRUNC | getattr(os, 'O_NOFOLLOW', 0), dir_fd=parent_fd)",  # noqa: E501 - emitted sandbox code is intentionally one line
            "            try:",
            "                write_all(restore_fd, previous)",
            "                os.fsync(restore_fd)",
            "            finally:",
            "                os.close(restore_fd)",
            "        except OSError as restore_exc:",
            "            raise StorageError(restore_exc.errno) from restore_exc",
            "        raise StorageError(exc.errno) from exc",
            "    try:",
            "        os.fsync(fd)",
            "    except OSError as exc:",
            "        cleanup_errno = exc.errno",
            "    finally:",
            "        if fd is not None:",
            "            os.close(fd)",
            "    try:",
            "        fsync_directory(parent_fd)",
            "    except StorageError as exc:",
            "        cleanup_errno = exc.errno",
            "    return os.stat(name, dir_fd=parent_fd, follow_symlinks=False), cleanup_errno",
            "try:",
            "    try:",
            "        base_fds, root_fd = open_chain(create=operation in ('write', 'append'))",
            "    except FileNotFoundError:",
            "        if relative == '.' and operation == 'list':",
            "            respond({'ok': True, 'entries': [], 'truncated': False})",
            "        if relative == '.' and operation == 'stat':",
            "            respond({'ok': True, 'entry': None})",
            "        raise",
            "    relative_parts = split_relative(relative)",
            "    if operation == 'list':",
            "        target_fds, target_fd = open_parent(root_fd, relative_parts)",
            "        try:",
            "            candidates = []",
            "            with os.scandir(target_fd) as scanner:",
            "                for item in scanner:",
            "                    child_relative = item.name if relative == '.' else f'{relative}/{item.name}'",
            "                    if after and child_relative <= after:",
            "                        continue",
            "                    candidate = (child_relative, item.name)",
            "                    if len(candidates) < limit + 1:",
            "                        candidates.append(candidate)",
            "                        continue",
            "                    largest = max(range(len(candidates)), key=lambda index: candidates[index][0])",
            "                    if child_relative < candidates[largest][0]:",
            "                        candidates[largest] = candidate",
            "            candidates.sort(key=lambda value: value[0])",
            "            selected = candidates[:limit]",
            "            entries = []",
            "            for child_relative, child_name in selected:",
            "                child_stat = os.stat(child_name, dir_fd=target_fd, follow_symlinks=False)",
            "                entries.append(entry_for(child_stat, child_relative))",
            "            truncated = len(candidates) > limit",
            "            next_cursor = selected[-1][0] if truncated and selected else None",
            "        finally:",
            "            close_all(target_fds)",
            "        respond({'ok': True, 'entries': entries, 'truncated': truncated, 'next_cursor': next_cursor})",
            "    if operation == 'stat':",
            "        if not relative_parts:",
            "            respond({'ok': True, 'entry': entry_for(os.fstat(root_fd), '.')})",
            "        parent_fds, parent_fd = open_parent(root_fd, relative_parts[:-1])",
            "        try:",
            "            try:",
            "                target_stat = os.stat(relative_parts[-1], dir_fd=parent_fd, follow_symlinks=False)",
            "            except FileNotFoundError:",
            "                if allow_missing:",
            "                    respond({'ok': True, 'entry': None})",
            "                raise",
            "            if stat.S_ISLNK(target_stat.st_mode):",
            "                fail('unsafe')",
            "            respond({'ok': True, 'entry': entry_for(target_stat, relative)})",
            "        finally:",
            "            close_all(parent_fds)",
            "    if operation in ('read', 'read_page'):",
            "        if not relative_parts:",
            "            fail('is_directory')",
            "        parent_fds, parent_fd = open_parent(root_fd, relative_parts[:-1])",
            "        fd = None",
            "        try:",
            "            target_stat = os.stat(relative_parts[-1], dir_fd=parent_fd, follow_symlinks=False)",
            "            if stat.S_ISLNK(target_stat.st_mode):",
            "                fail('unsafe')",
            "            if stat.S_ISDIR(target_stat.st_mode):",
            "                fail('is_directory')",
            "            if target_stat.st_size > max_bytes:",
            "                fail('read_bound')",
            "            if operation == 'read':",
            "                read_offset = 0",
            "                read_limit = max_bytes + 1",
            "            else:",
            "                if type(offset) is not int or offset < 0 or offset > target_stat.st_size:",
            "                    fail('cursor')",
            "                read_offset = offset",
            "                read_limit = min(target_stat.st_size - read_offset, max_chars * 4 + 4)",
            "            flags = os.O_RDONLY | getattr(os, 'O_NOFOLLOW', 0)",
            "            fd = os.open(relative_parts[-1], flags, dir_fd=parent_fd)",
            "            if operation == 'read_page':",
            "                os.lseek(fd, read_offset, os.SEEK_SET)",
            "            data = b''",
            "            while len(data) < read_limit:",
            "                chunk = os.read(fd, read_limit - len(data))",
            "                if not chunk:",
            "                    break",
            "                data += chunk",
            "        except FileNotFoundError:",
            "            fail('not_found')",
            "        finally:",
            "            if fd is not None:",
            "                os.close(fd)",
            "            close_all(parent_fds)",
            "        if operation == 'read' and len(data) > max_bytes:",
            "            fail('read_bound')",
            "        try:",
            "            content, valid_bytes = decode_page(data)",
            "        except UnicodeDecodeError:",
            "            fail('invalid_utf8')",
            "        if operation == 'read':",
            "            respond({'ok': True, 'content': content})",
            "        if len(content) > max_chars:",
            "            content = content[:max_chars]",
            "        consumed = len(content[:max_chars].encode('utf-8'))",
            "        next_offset = read_offset + consumed",
            "        eof = next_offset >= target_stat.st_size",
            "        respond({'ok': True, 'content': content, 'byte_size': target_stat.st_size, 'next_offset': next_offset, 'eof': eof})",  # noqa: E501 - emitted sandbox code is intentionally one line
            "    if operation == 'append':",
            "        payload = base64.b64decode(content_b64.encode('ascii'))",
            "        if len(payload) > max_bytes:",
            "            fail('too_large')",
            "        warnings = []",
            "        parent_fds, parent_fd = open_parent(root_fd, relative_parts[:-1], create=True)",
            "        fd = None",
            "        try:",
            "            try:",
            "                existing_stat = os.stat(relative_parts[-1], dir_fd=parent_fd, follow_symlinks=False)",
            "            except FileNotFoundError:",
            "                existing_stat = None",
            "            if existing_stat is not None:",
            "                if stat.S_ISLNK(existing_stat.st_mode):",
            "                    fail('unsafe')",
            "                if stat.S_ISDIR(existing_stat.st_mode):",
            "                    fail('is_directory')",
            "            flags = os.O_WRONLY | os.O_CREAT | os.O_APPEND | getattr(os, 'O_NOFOLLOW', 0)",
            "            fd = os.open(relative_parts[-1], flags, 0o600, dir_fd=parent_fd)",
            "            current_size = os.fstat(fd).st_size",
            "            if current_size + len(payload) > max_bytes:",
            "                fail('too_large')",
            "            write_all(fd, payload)",
            "            os.fsync(fd)",
            "            written_stat = os.fstat(fd)",
            "            try:",
            "                fsync_directory(parent_fd)",
            "            except StorageError as exc:",
            "                warnings.append({'code': 'cleanup_failed', 'errno': exc.errno})",
            "        finally:",
            "            if fd is not None:",
            "                os.close(fd)",
            "            close_all(parent_fds)",
            "        response = {'ok': True, 'entry': entry_for(written_stat, relative)}",
            "        if warnings:",
            "            response['warnings'] = warnings",
            "        respond(response)",
            "    if operation == 'write':",
            "        payload = base64.b64decode(content_b64.encode('ascii'))",
            "        if len(payload) > max_bytes:",
            "            fail('too_large')",
            "        fallback_overwrite = False",
            "        warnings = []",
            "        parent_fds, parent_fd = open_parent(root_fd, relative_parts[:-1], create=True)",
            "        try:",
            "            try:",
            "                existing_stat = os.stat(relative_parts[-1], dir_fd=parent_fd, follow_symlinks=False)",
            "            except FileNotFoundError:",
            "                existing_stat = None",
            "            if existing_stat is not None:",
            "                if stat.S_ISLNK(existing_stat.st_mode):",
            "                    fail('unsafe')",
            "                if stat.S_ISDIR(existing_stat.st_mode):",
            "                    fail('is_directory')",
            "                if not overwrite:",
            "                    fail('conflict')",
            "                try:",
            "                    written_stat = replace_existing(parent_fd, relative_parts[-1], payload)",
            "                except ReplacementUnsupported:",
            "                    previous = read_existing(parent_fd, relative_parts[-1], max_bytes)",
            "                    written_stat = overwrite_existing_direct(parent_fd, relative_parts[-1], payload, previous)",  # noqa: E501 - emitted sandbox code is intentionally one line
            "                    fallback_overwrite = True",
            "            else:",
            "                written_stat = publish_new(parent_fd, relative_parts[-1], payload)",
            "        finally:",
            "            close_all(parent_fds)",
            "        cleanup_errno = None",
            "        if fallback_overwrite:",
            "            warnings.append({'code': 'non_atomic_overwrite'})",
            "        if type(written_stat) is tuple and len(written_stat) == 2:",
            "            written_stat, cleanup_errno = written_stat",
            "        response = {'ok': True, 'entry': entry_for(written_stat, relative)}",
            "        if cleanup_errno is not None:",
            "            warnings.append({'code': 'cleanup_failed', 'errno': cleanup_errno})",
            "        if warnings:",
            "            response['warnings'] = warnings",
            "        respond(response)",
            "    fail('unsupported')",
            "except FileNotFoundError:",
            "    fail('not_found')",
            "except FileExistsError:",
            "    fail('conflict')",
            "except IsADirectoryError:",
            "    fail('is_directory')",
            "except NotADirectoryError:",
            "    fail('not_directory')",
            "except UnsafePath:",
            "    fail('unsafe')",
            "except StorageError as exc:",
            "    fail('unsupported_storage', errno=exc.errno)",
            "except OSError:",
            "    fail('unsafe')",
            "finally:",
            "    close_all(base_fds if 'base_fds' in locals() else [])",
        )
    )
    return code


def decode_workspace_agent_response(response: Any, relative: str) -> dict[str, object]:
    if int(getattr(response, "exit_code", 1)) != 0:
        raise ValueError("workspace path is unsafe")
    try:
        payload = json.loads(str(getattr(response, "result", "")))
    except (TypeError, ValueError) as exc:
        raise ValueError("workspace path is unsafe") from exc
    if payload.get("ok") is not True:
        _raise_workspace_error(payload, relative)
    return payload


def run_workspace_agent(sandbox: Any, **arguments: Any) -> dict[str, object]:
    relative = str(arguments.get("relative") or "")
    code = build_workspace_agent_code(**arguments)
    return decode_workspace_agent_response(sandbox.process.code_run(code), relative)


async def run_workspace_agent_async(sandbox: Any, **arguments: Any) -> dict[str, object]:
    relative = str(arguments.get("relative") or "")
    code = build_workspace_agent_code(**arguments)
    response = await sandbox.process.code_run(code)
    return decode_workspace_agent_response(response, relative)


def _raise_workspace_error(payload: dict[str, object], relative: str) -> None:
    error = str(payload.get("error") or "")
    path_error = _PATH_ERRORS.get(error)
    if path_error is not None:
        raise path_error(relative)
    value_error = _VALUE_ERRORS.get(error)
    if value_error is not None:
        raise ValueError(value_error)
    if error == "unsupported_storage":
        raise WorkspaceAgentStorageError(str(payload.get("errno") or "unknown"))
    raise ValueError("workspace path is unsafe")
