import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { StreamLifecycle } from "../fleet-turn-stream.js";
import { parseUIChunk } from "../sse.js";

/**
 * Golden-stream cross-validation: the fixture is generated by the backend
 * projector (`scripts/generate_stream_fixture.py`, `make stream-sync`) with the
 * exact wire serialization FastAPI emits. Every line must survive the TUI's
 * hand-written validator (`parseUIChunk`) AND the strict ordering grammar
 * (`StreamLifecycle`) — the same code paths a live turn display exercises.
 * If the backend stops emitting a shape or order the TUI accepts, this test
 * fails at CI time instead of mid-turn in a terminal.
 */

const FIXTURE = new URL("./fixtures/turn-stream.jsonl", import.meta.url);

const ALL_LIVE_CHUNK_TYPES = [
  "start",
  "start-step",
  "finish-step",
  "reasoning-start",
  "reasoning-delta",
  "reasoning-end",
  "data-status",
  "data-skill",
  "data-rlm-code",
  "data-rlm-output",
  "tool-input-available",
  "tool-output-available",
  "tool-output-error",
  "data-attachment",
  "data-warning",
  "data-artifact",
  "data-usage",
  "data-structured-result",
  "text-start",
  "text-delta",
  "text-end",
  "finish",
  "abort",
  "error",
] as const;

function fixtureLines(): string[] {
  return readFileSync(FIXTURE, "utf8")
    .split("\n")
    .filter((line) => line.length > 0);
}

describe("backend turn-stream fixture", () => {
  it("every chunk passes the TUI validator and the stream-ordering grammar", () => {
    const lines = fixtureLines();
    expect(lines.length).toBeGreaterThan(0);

    let lifecycle: StreamLifecycle | null = null;
    let segments = 0;
    for (const line of lines) {
      if (line === "[DONE]") {
        expect(lifecycle, "unexpected [DONE] outside a stream").not.toBeNull();
        // Mirror the live path: the sentinel goes through accept() (sets the
        // done flag) before the terminal-state assertion.
        lifecycle?.accept("[DONE]");
        lifecycle?.assertComplete();
        lifecycle = null;
        segments += 1;
        continue;
      }
      const chunk = parseUIChunk(line);
      lifecycle ??= new StreamLifecycle();
      lifecycle.accept(chunk);
    }

    // Every stream segment must be terminated with its [DONE].
    expect(lifecycle).toBeNull();
    expect(segments).toBeGreaterThan(0);
  });

  it("covers every live chunk type the TUI recognizes", () => {
    const types = new Set(
      fixtureLines()
        .filter((line) => line !== "[DONE]")
        .map((line) => (JSON.parse(line) as { type: string }).type),
    );
    expect([...types].sort()).toEqual([...ALL_LIVE_CHUNK_TYPES].sort());
  });
});
