"""Generate the policy-derived configuration environment reference documentation."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fleet_rlm.config.loader import (
    load_configuration_environment_contract,
)

_REPO_ROOT = Path(__file__).resolve().parents[1]
_OUTPUT = _REPO_ROOT / "docs" / "reference" / "configuration-environment.md"
_HEADER = (
    "<!-- Generated by uv run python scripts/generate_configuration_reference.py generate. Do not edit manually. -->"
)


def _names(values: tuple[str, ...]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "—"


def render() -> str:
    """Render the environment reference from the committed single policy."""
    contract = load_configuration_environment_contract()
    rows = [
        _HEADER,
        "# Configuration environment reference",
        "",
        "Generated from `config/fleet.toml`, the source of truth for the single runtime configuration.",
        "",
        "| Setting | Configured value |",
        "| --- | --- |",
        f"| Runtime | `{contract.runtime_environment}` |",
        f"| Provider | {contract.provider} |",
        f"| Root model | `{contract.root_model}` |",
        f"| Sub model | `{contract.sub_model}` |",
        f"| Root / Sub max tokens | {contract.root_max_tokens or 'default'} / {contract.sub_max_tokens or 'default'} |",
        f"| Fleet child recursion | {'enabled' if contract.recursion_enabled else 'disabled'} |",
        f"| MLflow | {contract.mlflow_tracking_uri if contract.mlflow_tracing_enabled else 'disabled'} |",
        f"| Provider environment names | {_names(contract.provider_environment_names)} |",
        f"| Database environment name | {_names((contract.database_url_env,) if contract.database_url_env else ())} |",
        f"| Snapshot environment names | {_names(contract.daytona_snapshot_environment_names)} |",
        f"| Optional MLflow environment names | {_names(contract.mlflow_environment_names)} |",
        "",
        "Startup requires a configured database URL at Alembic head. Local SQLite and PostgreSQL are supported; "
        "the explicit Lakebase preflight additionally enforces its TLS and role requirements.",
        "",
        "Live verification requires operator authorization and the configured provider credentials. "
        "Native-only checks require `rlm.recursion_enabled = false`; recursive checks require it enabled. "
        "Checks never select another configuration. Isolated proofs use temporary database URLs as documented.",
        "",
    ]
    return "\n".join(rows)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "check"))
    parser.add_argument("--output", type=Path, default=_OUTPUT)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output = args.output.resolve()
    rendered = render()
    if args.command == "generate":
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"generated {output}")
        return 0
    if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
        print(f"configuration reference is stale: {output}", file=sys.stderr)
        return 1
    print(f"configuration reference is current: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
