"""Generate the policy-derived provider/profile matrix documentation."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fleet_rlm.config import ProfileEnvironmentContract, active_profile_contract, load_profile_environment_contracts

_REPO_ROOT = Path(__file__).resolve().parents[1]
_OUTPUT = _REPO_ROOT / "docs" / "reference" / "profile-matrix.md"
_HEADER = "<!-- Generated by uv run python scripts/generate_profile_matrix.py generate. Do not edit manually. -->"


def _names(values: tuple[str, ...]) -> str:
    return ", ".join(f"`{value}`" for value in values) or "—"


def _extra_policy_names(contract: ProfileEnvironmentContract) -> str:
    provider = set(contract.provider_environment_names)
    extra = tuple(name for name in contract.managed_policy_environment_names if name not in provider)
    return _names(extra)


def _mlflow(contract: ProfileEnvironmentContract) -> str:
    if not contract.mlflow_tracing_enabled:
        return "disabled"
    return contract.mlflow_tracking_uri or "policy default"


def render() -> str:
    """Render the matrix from the committed TOML policy."""
    active = active_profile_contract().name
    rows = [
        _HEADER,
        "# Runtime profile matrix",
        "",
        "This file is generated from `config/fleet.toml`; the TOML policy is the source of truth. "
        f"The active default is `{active}`.",
        "",
        "Provider environment names are the only values required by the credentialed live verifier. "
        + "Managed-policy names are additionally required when `daytona-managed` is selected.",
        "",
        "| Profile | Default | Provider | Root/Sub model | Root/Sub max tokens | Recursion | MLflow | "
        + "Provider environment names | Managed-policy environment names |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for contract in load_profile_environment_contracts():
        default = "yes" if contract.name == active else "no"
        models = f"`{contract.root_model}` / `{contract.sub_model}`"
        tokens = f"{contract.root_max_tokens or 'default'} / {contract.sub_max_tokens or 'default'}"
        recursion = "enabled" if contract.recursion_enabled else "disabled"
        rows.append(
            f"| `{contract.name}` | {default} | {contract.provider} | {models} | {tokens} | {recursion} | "
            f"{_mlflow(contract)} | {_names(contract.provider_environment_names)} | {_extra_policy_names(contract)} |"
        )
    rows.extend(
        [
            "",
            "The verifier uses the selected row's provider environment names and never checks a hard-coded provider "
            + "credential. `FLEET_DATABASE_URL` is replaced by a temporary SQLite URL in the live proof; it is a "
            + "required selected-policy value only for the managed profile.",
            "",
        ]
    )
    return "\n".join(rows)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "check"))
    parser.add_argument("--output", type=Path, default=_OUTPUT)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output = args.output.resolve()
    rendered = render()
    if args.command == "generate":
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"generated {output}")
        return 0
    if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
        print(f"profile matrix is stale: {output}", file=sys.stderr)
        return 1
    print(f"profile matrix is current: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
