import { createRouter } from '@tanstack/react-router'

// Import the generated route tree (this file will be auto-generated by the Vite plugin)
import { routeTree } from './routeTree.gen'

// Create a new router instance
export const router = createRouter({ routeTree })

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
