import { createRouter } from "@tanstack/react-router";

// Import the generated route tree (this file will be auto-generated by the Vite plugin)
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
  });
}

// Keep a singleton export for legacy tests and non-Start entrypoints.
export const router = getRouter();

// Register the router instance for type safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
