/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorkspaceRouteImport } from './routes/app/workspace'
import { Route as AppVolumesRouteImport } from './routes/app/volumes'
import { Route as AppTaxonomyRouteImport } from './routes/app/taxonomy'
import { Route as AppSkillsRouteImport } from './routes/app/skills'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMemoryRouteImport } from './routes/app/memory'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppTaxonomySkillIdRouteImport } from './routes/app/taxonomy.$skillId'
import { Route as AppSkillsSkillIdRouteImport } from './routes/app/skills.$skillId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppVolumesRoute = AppVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxonomyRoute = AppTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxonomySkillIdRoute = AppTaxonomySkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => AppTaxonomyRoute,
} as any)
const AppSkillsSkillIdRoute = AppSkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => AppSkillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRouteWithChildren
  '/app/taxonomy': typeof AppTaxonomyRouteWithChildren
  '/app/volumes': typeof AppVolumesRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/': typeof AppIndexRoute
  '/app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/app/taxonomy/$skillId': typeof AppTaxonomySkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRouteWithChildren
  '/app/taxonomy': typeof AppTaxonomyRouteWithChildren
  '/app/volumes': typeof AppVolumesRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app': typeof AppIndexRoute
  '/app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/app/taxonomy/$skillId': typeof AppTaxonomySkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRouteWithChildren
  '/app/taxonomy': typeof AppTaxonomyRouteWithChildren
  '/app/volumes': typeof AppVolumesRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/': typeof AppIndexRoute
  '/app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/app/taxonomy/$skillId': typeof AppTaxonomySkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/app'
    | '/login'
    | '/logout'
    | '/settings'
    | '/signup'
    | '/app/analytics'
    | '/app/memory'
    | '/app/settings'
    | '/app/skills'
    | '/app/taxonomy'
    | '/app/volumes'
    | '/app/workspace'
    | '/app/'
    | '/app/skills/$skillId'
    | '/app/taxonomy/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/login'
    | '/logout'
    | '/settings'
    | '/signup'
    | '/app/analytics'
    | '/app/memory'
    | '/app/settings'
    | '/app/skills'
    | '/app/taxonomy'
    | '/app/volumes'
    | '/app/workspace'
    | '/app'
    | '/app/skills/$skillId'
    | '/app/taxonomy/$skillId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/app'
    | '/login'
    | '/logout'
    | '/settings'
    | '/signup'
    | '/app/analytics'
    | '/app/memory'
    | '/app/settings'
    | '/app/skills'
    | '/app/taxonomy'
    | '/app/volumes'
    | '/app/workspace'
    | '/app/'
    | '/app/skills/$skillId'
    | '/app/taxonomy/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/volumes': {
      id: '/app/volumes'
      path: '/volumes'
      fullPath: '/app/volumes'
      preLoaderRoute: typeof AppVolumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taxonomy': {
      id: '/app/taxonomy'
      path: '/taxonomy'
      fullPath: '/app/taxonomy'
      preLoaderRoute: typeof AppTaxonomyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taxonomy/$skillId': {
      id: '/app/taxonomy/$skillId'
      path: '/$skillId'
      fullPath: '/app/taxonomy/$skillId'
      preLoaderRoute: typeof AppTaxonomySkillIdRouteImport
      parentRoute: typeof AppTaxonomyRoute
    }
    '/app/skills/$skillId': {
      id: '/app/skills/$skillId'
      path: '/$skillId'
      fullPath: '/app/skills/$skillId'
      preLoaderRoute: typeof AppSkillsSkillIdRouteImport
      parentRoute: typeof AppSkillsRoute
    }
  }
}

interface AppSkillsRouteChildren {
  AppSkillsSkillIdRoute: typeof AppSkillsSkillIdRoute
}

const AppSkillsRouteChildren: AppSkillsRouteChildren = {
  AppSkillsSkillIdRoute: AppSkillsSkillIdRoute,
}

const AppSkillsRouteWithChildren = AppSkillsRoute._addFileChildren(
  AppSkillsRouteChildren,
)

interface AppTaxonomyRouteChildren {
  AppTaxonomySkillIdRoute: typeof AppTaxonomySkillIdRoute
}

const AppTaxonomyRouteChildren: AppTaxonomyRouteChildren = {
  AppTaxonomySkillIdRoute: AppTaxonomySkillIdRoute,
}

const AppTaxonomyRouteWithChildren = AppTaxonomyRoute._addFileChildren(
  AppTaxonomyRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRouteWithChildren
  AppTaxonomyRoute: typeof AppTaxonomyRouteWithChildren
  AppVolumesRoute: typeof AppVolumesRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRouteWithChildren,
  AppTaxonomyRoute: AppTaxonomyRouteWithChildren,
  AppVolumesRoute: AppVolumesRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
